### ISSUE TITLE
Remove calculator.py

### ISSUE THREAD

**Issue by bioniclambda** [1Wyatt1/Calculators#11]
Since `calculator.py` is now essentially a copy of `bettercalc.py`, I think it could be good to remove `calculator.py` and not have two indistinct calculators. "Why not the other way around?" You may ask, well, I figured since `bettercalc.py` was created with its set of features first (no splitting, Modulo operator, etc.), we should remove the clone of it, `calculator.py`. However, if you think otherwise, you can message me on Discord at `bioniclambda#2556`.

**Comment by argvsc47** [comment]
_b r u h_ calculator.py was the first one made, and bettercalc is _the_ copy tho tbh idrc do ur stuff

**Comment by bioniclambda** [comment]
I created `calculator.py` and `bettercalc.py` was not a copy, but a better version. Then you did the exact things I did, so `calculator.py` is the copy.
